<!--<?php
$sistema = Zend_Registry::get('sistema');
$usuario = Fmo_Model_Seguridad::getUsuarioSesion();
?>
<h1 style="text-transform: uppercase; text-align: center;">
    <?php echo $this->escape($sistema['titulo']), ' (', $this->escape($sistema['siglado']), ')'; ?>
</h1>
<p style="margin-left: 10px; margin-right: 10px; text-align: justify;">
<?php
if (isset($usuario->nombre, $usuario->apellido)):
    echo '¡Enhorabuena <b>';
    echo ucwords(strtolower($usuario->nombre . ' ' . $usuario->apellido));
    echo '</b>! has entrado al ';
endif; ?><b><?php echo $sistema['titulo']; ?> (<?php echo strtoupper($sistema['siglado']); ?>)
    
<div align="right">   
<p>
    Versión Anterior SJUD : <a href="http://www.framework.zend.com/"><?php echo $this->img('Va_3.png', array('alt' => 'Versión Anterior')); ?></a>
</p>
</div>-->

<?php
/* @var $container Zend_Navigation_Container */
$container = $this->navigation()->getContainer();

static $list = array(
    'MIEMBROS DE JUNTA DIRECTIVA' => array(
        'Nuevo Miembro de Junta Directiva'     => 'nuevo_miembro.png',
        'Miembro Actual de Junta Directiva'    => 'miembro_actual.png',
        'Miembro Anterior de Junta Directiva'  => 'miembros_anteriores.png',
        'Listado Gcia.Gral/Coord.'  => 'listado.png',
        'Nuevo Cargo de Junta Directiva'  => 'cargo.png',
        'Nuevo Estado Pto. Cuenta/Resolución'  => 'nuevo1.png',
        'Nuevo Tipo de Reunión'  => 'docum.png',
        
     )
);
$this->headStyle()->captureStart();
echo <<<'EOT'

p.texto_informacion {
    font-size: small;
}
   
h1.titulo_sistema {
    background-color: #FF8500;
    border: 1px solid #B29C6B;
    -webkit-border-radius: 4px;
    -moz-border-radius: 4px;
    border-radius: 4px;
    padding: 3px;
    color: #F7F7F7;
}
    
div.agrupador {
    border: 1px solid black;
    display: inline-block;
    padding: 8px;
    -webkit-border-radius: 4px;
    -moz-border-radius: 4px;
    border-radius: 4px;
    border: 1px solid gray;
    background-color: #E7E7E7;
    margin-bottom: 8px;
    margin-left: 4px;
}

div.agrupador > h2 {
    margin: 0px;
    width: 100%;
    margin-bottom: 4px;
}
   
div.caja_redondeada {
    width: 120px;
    height: 145px;
    -webkit-border-radius: 8px;
    -moz-border-radius: 8px;
    border-radius: 8px;
    border: 3px solid #5C0000;
    -moz-box-shadow: #2B2B2B 2px 2px 2px; 
    -webkit-box-shadow: #2B2B2B 2px 2px 2px;    
    box-shadow: #2B2B2B 2px 2px 2px;
    background-color: #F5F3EC;
    display: inline-block;
    float: left;
    margin: 4px;
}

div.caja_redondeada:hover {
    background-color: #F1E8CB;
}

div.caja_redondeada:hover > a {
    color: #5C0000;
    text-decoration: underline;
}

div.caja_redondeada > a {
    text-decoration: none;
    color: black;
    text-transform: uppercase;
    font-weight: bolder;
}

div.caja_redondeada > a > img {
    display: block;
    margin: auto;
    border: 0px;
}

div.caja_redondeada > a > span {
    display: block;
    height: 24px;
    text-align: center;    
    border-top: 1px solid #5C0000;
    font-size: x-small;
    padding: 2px;
}

EOT;
$this->headStyle()->captureEnd();
echo '<h1 align="center" class="titulo_sistema">', $this->stringToUpper($this->sistema['titulo']), ' (', $this->stringToUpper($this->sistema['siglado']), ')</h1>', PHP_EOL;
echo '<div align="center">';
foreach ($list as $titulo => $opciones):    
    
    echo '<div class="agrupador">', PHP_EOL,
         '<h2 align="center">', $this->escape($titulo), '</h2>', PHP_EOL;

    foreach ($opciones as $id => $imgsrc):

        $resource = $container->findOneBy('id', $id);
    
        if ($resource instanceof Zend_Navigation_Page):

            $url = $resource instanceof Zend_Navigation_Page_Mvc
                 ? $this->createUrlByMvc($resource)
                 : $resource->get('uri');
            
            echo '<div class="caja_redondeada" title="', $this->escape($resource->get('title')), '">', PHP_EOL,
                 '<a href="', $url, '">', $this->img($imgsrc, array('alt' => $resource->get('label'))), '<span>', $this->escape($resource->get('label')), '</span></a>', PHP_EOL,
                 '</div>', PHP_EOL;
        endif;
    endforeach;
    echo '</div>', PHP_EOL;
endforeach;
echo '</div>';


//<?php href="javascript:window.history.go(-1);"><?php echo $this->img('vol_1.png', array('alt' => 'Volver a la Pagina Principal')); ?></a>

<!--<a href="/~fmo16014/sjud/fmo/autenticacion/desconectarse" title="Cerrar sesión">
<img src="/~fmo16014/sjud/../zendlib/public/images/ico_puerta_abierta.png" alt="ico_puerta_abierta.png" width="16" height="16"></a>-->

-<a href="/../sjud/fmo/autenticacion/desconectarse" title="Cerrar sesión">
<img src="../../../zendlib/public/images/salida2.png" alt="salida2.png" align="right" ></a>


<!--   <div align="right">   
   <p>
   <a href="http://servicios.ferrominera.gob.ve/portal-servicios/"><?php echo $this->img('salida2.png', array('alt' => 'Salir de la Pagina Principal'));?></a>
   <!--<a href="javascript:window.close();"><?php echo $this->img('salida2.png', array('alt' => 'Salir de la Pagina Principal')); ?></a>
   <a href="javascript:window.close();"><?php echo $this->img('vol_1.png', array('alt' => 'Volver a la Pagina Principal')); ?></a>
    
    </p>
    </div>
   


