<?php


 /* Vista para agregar la junta directiva.
 * 
 * @author manuelry <manuelry@ferrominera.gob.ve>
  */    

if ($this->form instanceof Application_Form_Miembro):
    $tituloForm = $this->form->getLegend();
    echo $this->form->renderForm(false);
?>
 <!-- Icono volver a la página principal-->

    <table class="general" summary="Agregar Nueva Junta Directiva" style="width: 60%" id="tabla1">
        <caption>AGREGAR MIEMBROS A LA JUNTA DIRECTIVA</caption>
    </table>
    
<br></br>

    <table class="general" summary="<?php echo $this->escape($tituloForm); ?>" style="width: 35%" id="tabla2">
        <tr>
            <th style="width: 20%">
                <?php echo $this->form->getElement(Application_Form_Miembro::E_FECHA)->getLabel(); ?>
            </th>
            <td style="width: 10%">
                <?php 
                    echo $this->form->getElement(Application_Form_Miembro::E_FECHA)->getValue();
                    
                ?>   
            </td>
        </tr>  
        <tr>
            <th style="width: 20%">
                <?php echo $this->form->getElement(Application_Form_Miembro::E_CARGO)->getLabel(); ?>
            </th>
            <td style="width: 10%">
                <?php
                    echo $this->form->setDefault(Application_Form_Miembro::E_CARGO,$this->idCargoView)
                         ->getElement(Application_Form_Miembro::E_CARGO)->renderViewHelper(),
                         $this->form->getElement(Application_Form_Miembro::E_CARGO)->renderErrors();
                    
                ?>   
            </td>
            
        </tr>
        <tr>
         <th style="width: 20%">
                <?php echo $this->form->getElement(Application_Form_Miembro::E_FICHA)->getLabel(); ?>
            </th>
            <td style="width: 10%">
                <?php
                    echo $this->form->setDefault(Application_Form_Miembro::E_FICHA,$this->idFichaView)
                         ->getElement(Application_Form_Miembro::E_FICHA)->renderViewHelper(),
                         $this->form->getElement(Application_Form_Miembro::E_FICHA)->renderErrors();
                         
                ?>
                    
                       
            </td>
        </tr> 
        <tr>
            <th style="width: 20%">
                <?php echo $this->form->getElement(Application_Form_Miembro::E_CEDULA)->getLabel(); ?>
            </th>
            <td style="width: 10%">
                <?php
                    echo $this->form->getElement(Application_Form_Miembro::E_CEDULA)->renderViewHelper(),
                         $this->form->getElement(Application_Form_Miembro::E_CEDULA)->renderDescription(),
                         $this->form->getElement(Application_Form_Miembro::E_CEDULA)->renderErrors();
                     ?> 
            </td>
                      
        </tr>
        
        <tr>
            <th style="width: 20%">
                <?php echo $this->form->getElement(Application_Form_Miembro::E_NOMBRE)->getLabel(); ?>
            </th>
            <td style="width: 10%">
                <?php
                    echo $this->form->getElement(Application_Form_Miembro::E_NOMBRE)->renderViewHelper(),
                         $this->form->getElement(Application_Form_Miembro::E_NOMBRE)->renderDescription(),
                         $this->form->getElement(Application_Form_Miembro::E_NOMBRE)->renderErrors();
                    ?> 
            </td>
                      
        </tr>      
      
         
    </table> 
    
    <p align="center"><?php
        echo $this->form->getElement(Application_Form_Miembro::E_BUSCAR)->renderViewHelper();
        echo $this->form->getElement(Application_Form_Miembro::E_AGREGAR)->renderViewHelper();
        echo $this->form->getElement(Application_Form_Miembro::E_CANCELAR)->renderViewHelper();
                      
        ?></p>
    <table class="general" summary="Miembros Actuales Junta Directiva" style="width: 60%" id="tabla1">
        <caption>Miembros Actuales Junta Directiva</caption>
        <thead>
            <tr>
                <th>N°</th>
                <th>Cargo</th>
                <th>Miembro</th>
                <th>Fecha</th>  
            </tr>    
        </thead>
        <tbody>  
           <?php 
           $consultaMiembros =  Application_Model_Miembros::getJuntaActual();
           
            if(!empty($consultaMiembros)):
               $contador = 0;
               foreach ($consultaMiembros as $index => $consultaMiembros):
                
               ?>
                    <tr>
                        <td align="center"><?php echo Zend_Locale_Format::toNumber( ++$contador); ?></td>
                        
                        <td align="center"><?php 
                        //Fmo_Logger::debug($consultaMiembros->id_cargo);
                        //$consultaCargo = Application_Model_Cargo::getDescriCargo($consultaMiembros->id_cargo);
                        //Fmo_Logger::debug($consultaCargo);
                        echo ($consultaMiembros->descripcion); ?></td>
                        <td align="center"><?php echo $this->escape($consultaMiembros->nombre); ?></td>
                        <td align="center"><?php 
                        $fecha_f = new Zend_Date($consultaMiembros->fecha_periodo);
                        echo $this->escape($fecha_f->toString('dd/MM/yyyy')); ?></td>
                    </tr>
                <?php 
                endforeach; else: ?>  
                <tr>
                    <td colspan="5" align="center">No se encontro el estado</td>
                </tr>
               <?php endif;?> 
               
        </tbody>
    </table>
   
<?php
endif;

